# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Field(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, field: str=None):  # noqa: E501
        """Field - a model defined in Swagger

        :param field: The field of this Field.  # noqa: E501
        :type field: str
        """
        self.swagger_types = {
            'field': str
        }

        self.attribute_map = {
            'field': 'field'
        }
        self._field = field

    @classmethod
    def from_dict(cls, dikt) -> 'Field':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Field of this Field.  # noqa: E501
        :rtype: Field
        """
        return util.deserialize_model(dikt, cls)

    @property
    def field(self) -> str:
        """Gets the field of this Field.


        :return: The field of this Field.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field: str):
        """Sets the field of this Field.


        :param field: The field of this Field.
        :type field: str
        """

        self._field = field
