version: "3"
volumes:
  youngres-db-data:
services:
  db:
    image: mongo:4.2
    volumes:
      - youngres-db-data:/data/db
      - ./game_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=games_db
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "8884:27017"
    expose:
      - "8884"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  gameplay:
    build:
      context: ./gameplay_api
      dockerfile: Dockerfile
    environment:
      # provide your credentials here
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE="games_db"
    ports:
      - "8882:8080"
    expose:
      - "8882"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  consumption:
    build:
      context: ./consumption_api
      dockerfile: Dockerfile
    environment:
      # provide your credentials here
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "8883:8080"
    expose:
      - "8883"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  visualization:
    build:
      context: ./visualization
      dockerfile: Dockerfile
    ports:
      - "8885:8080"
    expose:
      - "8885"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
