version: "3"
volumes:
  db-data:
  dummy-db:
services:
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "8884:27017"
    expose:
      - "8884"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  # ===========================================================================
  # this servide only exists for the dummy data database when move to production
  # is better to remove it
  dummydb:
    image: mongo
    volumes:
      - dummy-db:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  # ===========================================================================
  gameplay:
    image: youngres/youngres_gameplay_api:faf348b
    ports:
      - "8882:8080"
    expose:
      - "8882"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  consumption:
    image: youngres_consumption_api # youngres/youngres_consumption_api:2edeeb3
    environment:
      # provide your credentials here
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8883:8080"
    expose:
      - "8883"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
# ==== MOODLE INTEGRATION ======
  mariadb:
    image: 'mariadb'
    environment:
      - MYSQL_ROOT_PASSWORD=kamisama123
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=kamisama123
      - MYSQL_DATABASE=moodle
    volumes:
      - './mariadb:/var/lib/mysql'
      - './db.init:/docker-entrypoint-initdb.d'
  moodle:
    image: 'bitnami/moodle'
    ports:
      - '8878:8080'
      - '433:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=kamisama123
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_SKIP_BOOTSTRAP=True
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
