version: "3"
volumes:
  db-data:
services:
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "8884:27017"
    expose:
      - "8884"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  gameplay:
    image: gameplay_api_test_alfonso
    ports:
      - "8882:8080"
    expose:
      - "8882"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  consumption:
    image: consumption_api_test_alfonso
    ports:
      - "8883:8080"
    expose:
      - "8883"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
