version: "3"
volumes:
  db-data:
services:
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  gameplay:
    image: youngres/youngres_gameplay_api
    ports:
      - "8882:8080"
    expose:
      - "8882"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  consuption:
    image: youngres/youngres_consumption_api
    ports:
      - "8883:8080"
    expose:
      - "8883"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
