openapi: 3.0.0
info:
  title: YoungRes gameplay API
  description: Api meant to be consumed by the RPGMaker games.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost/gameplay
  description: SwaggerHub API Auto Mocking
security:
- basicAuth: []
paths:
  /savedVariables/:
    get:
      summary: Returns the value stored on a game variable named variableName if possible
      operationId: saved_variables_get
      parameters:
      - name: studentCode
        in: query
        description: code to identify a student
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: gameCode
        in: query
        description: code to identify a game
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: version
        in: query
        description: code to identify the version of a game
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: variableName
        in: query
        description: code to identify the variable stored on save state
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: The variable was found on the specified saved state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Wrong credentials
        "500":
          description: INternal server error with the error message
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Store/Update a variable with variableName and value value if possible.
        If the user has no saved state for a specific game a new saved state must
        be generated.
      operationId: saved_variables_post
      parameters:
      - name: studentCode
        in: query
        description: code to identify a student
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: gameCode
        in: query
        description: code to identify a game
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: version
        in: query
        description: code to identify the version of a game
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: variableName
        in: query
        description: code of the variable to be stored/updated
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: value
        in: query
        description: textual value to store on the saved state
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: The variable was stored/updated correctly
        "401":
          description: Wrong credentials
        "500":
          description: INternal server error with the error message
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /chapterStartScene/:
    get:
      summary: Returns the start scene of a chapter as a sceneID if possible
      operationId: chapter_start_scene_get
      parameters:
      - name: gameCode
        in: query
        description: code to identify a game
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: version
        in: query
        description: code to identify the version of a game
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: chapterCode
        in: query
        description: code to identify the chapter to get the scene of
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: The scene was found and its ID is being returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Wrong credentials
        "500":
          description: Internal server error with the error message
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /storeDecision/:
    post:
      summary: Store/Update a new user decision related to the event eventCode with
        the variables data  into the database.
      operationId: store_decision_post
      parameters:
      - name: studentCode
        in: query
        description: code to identify a student
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: eventCode
        in: query
        description: code to identify an event
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: decision
        in: query
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Decision'
      responses:
        "200":
          description: The decision was stored/updated correctly
        "401":
          description: Wrong credentials
        "500":
          description: Internal server error with the error message
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Entry:
      description: Object used as a entry of a general dictionary
      properties:
        key:
          type: string
        value:
          type: string
    Decision:
      type: object
      properties:
        decision:
          type: array
          items:
            $ref: '#/components/schemas/Entry'
    inline_response_200:
      type: object
      properties:
        value:
          type: string
          example: Girl
      example:
        value: Girl
    inline_response_200_1:
      type: object
      properties:
        value:
          type: string
          example: Map23
      example:
        value: Map23
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: swagger_server.controllers.authorization_controller.check_basicAuth
