# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Entry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, key: str=None, min_value: str=None, max_value: str=None, value: str=None):  # noqa: E501
        """Entry - a model defined in Swagger

        :param key: The key of this Entry.  # noqa: E501
        :type key: str
        :param min_value: The min_value of this Entry.  # noqa: E501
        :type min_value: str
        :param max_value: The max_value of this Entry.  # noqa: E501
        :type max_value: str
        """
        self.swagger_types = {
            'key': str,
            'min_value': str,
            'max_value': str,
            'value': str
        }

        self.attribute_map = {
            'key': 'key',
            'min_value': 'min_value',
            'max_value': 'max_value',
            'value': 'value'
        }
        self._key = key
        self._min_value = min_value
        self._max_value = max_value
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Entry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entry of this Entry.  # noqa: E501
        :rtype: Entry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this Entry.


        :return: The key of this Entry.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this Entry.


        :param key: The key of this Entry.
        :type key: str
        """

        self._key = key

    @property
    def min_value(self) -> str:
        """Gets the min_value of this Entry.


        :return: The min_value of this Entry.
        :rtype: str
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: str):
        """Sets the min_value of this Entry.


        :param min_value: The min_value of this Entry.
        :type min_value: str
        """

        self._min_value = min_value

    @property
    def max_value(self) -> str:
        """Gets the max_value of this Entry.


        :return: The max_value of this Entry.
        :rtype: str
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: str):
        """Sets the max_value of this Entry.


        :param max_value: The max_value of this Entry.
        :type max_value: str
        """

        self._max_value = max_value

    @property
    def value(self) -> str:
        """Gets the value of this Entry.


        :return: The value of this Entry.
        :rtype: str
        """
        return self._value

    @max_value.setter
    def value(self, value: str):
        """Sets the max_value of this Entry.


        :param value: The value of this Entry.
        :type max_value: str
        """

        self._value = value

