# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.decision import Decision  # noqa: F401,E501
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, decisions: List[Decision]=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param decisions: The decisions of this InlineResponse2003.  # noqa: E501
        :type decisions: List[Decision]
        """
        self.swagger_types = {
            'decisions': List[Decision]
        }

        self.attribute_map = {
            'decisions': 'decisions'
        }
        self._decisions = decisions

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def decisions(self) -> List[Decision]:
        """Gets the decisions of this InlineResponse2003.


        :return: The decisions of this InlineResponse2003.
        :rtype: List[Decision]
        """
        return self._decisions

    @decisions.setter
    def decisions(self, decisions: List[Decision]):
        """Sets the decisions of this InlineResponse2003.


        :param decisions: The decisions of this InlineResponse2003.
        :type decisions: List[Decision]
        """

        self._decisions = decisions
