# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.game import Game  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, games: List[Game]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param games: The games of this InlineResponse2002.  # noqa: E501
        :type games: List[Game]
        """
        self.swagger_types = {
            'games': List[Game]
        }

        self.attribute_map = {
            'games': 'games'
        }
        self._games = games

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def games(self) -> List[Game]:
        """Gets the games of this InlineResponse2002.


        :return: The games of this InlineResponse2002.
        :rtype: List[Game]
        """
        return self._games

    @games.setter
    def games(self, games: List[Game]):
        """Sets the games of this InlineResponse2002.


        :param games: The games of this InlineResponse2002.
        :type games: List[Game]
        """

        self._games = games
