# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.event import Event  # noqa: F401,E501
from swagger_server import util


class Chapter(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, chapter_code: str=None, chapter_description: str=None, number_events: int=None, events: List[Event]=None):  # noqa: E501
        """Chapter - a model defined in Swagger

        :param chapter_code: The chapter_code of this Chapter.  # noqa: E501
        :type chapter_code: str
        :param chapter_description: The chapter_description of this Chapter.  # noqa: E501
        :type chapter_description: str
        :param number_events: The number_events of this Chapter.  # noqa: E501
        :type number_events: int
        :param events: The events of this Chapter.  # noqa: E501
        :type events: List[Event]
        """
        self.swagger_types = {
            'chapter_code': str,
            'chapter_description': str,
            'number_events': int,
            'events': List[Event]
        }

        self.attribute_map = {
            'chapter_code': 'chapterCode',
            'chapter_description': 'chapterDescription',
            'number_events': 'numberEvents',
            'events': 'events'
        }
        self._chapter_code = chapter_code
        self._chapter_description = chapter_description
        self._number_events = number_events
        self._events = events

    @classmethod
    def from_dict(cls, dikt) -> 'Chapter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Chapter of this Chapter.  # noqa: E501
        :rtype: Chapter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chapter_code(self) -> str:
        """Gets the chapter_code of this Chapter.

        code that identifies a chapter inside a video game.  # noqa: E501

        :return: The chapter_code of this Chapter.
        :rtype: str
        """
        return self._chapter_code

    @chapter_code.setter
    def chapter_code(self, chapter_code: str):
        """Sets the chapter_code of this Chapter.

        code that identifies a chapter inside a video game.  # noqa: E501

        :param chapter_code: The chapter_code of this Chapter.
        :type chapter_code: str
        """

        self._chapter_code = chapter_code

    @property
    def chapter_description(self) -> str:
        """Gets the chapter_description of this Chapter.

        short description of a chapter.  # noqa: E501

        :return: The chapter_description of this Chapter.
        :rtype: str
        """
        return self._chapter_description

    @chapter_description.setter
    def chapter_description(self, chapter_description: str):
        """Sets the chapter_description of this Chapter.

        short description of a chapter.  # noqa: E501

        :param chapter_description: The chapter_description of this Chapter.
        :type chapter_description: str
        """

        self._chapter_description = chapter_description

    @property
    def number_events(self) -> int:
        """Gets the number_events of this Chapter.

        Number of events in a chapter  # noqa: E501

        :return: The number_events of this Chapter.
        :rtype: int
        """
        return self._number_events

    @number_events.setter
    def number_events(self, number_events: int):
        """Sets the number_events of this Chapter.

        Number of events in a chapter  # noqa: E501

        :param number_events: The number_events of this Chapter.
        :type number_events: int
        """

        self._number_events = number_events

    @property
    def events(self) -> List[Event]:
        """Gets the events of this Chapter.

        list with all the events of the chapter.  # noqa: E501

        :return: The events of this Chapter.
        :rtype: List[Event]
        """
        return self._events

    @events.setter
    def events(self, events: List[Event]):
        """Sets the events of this Chapter.

        list with all the events of the chapter.  # noqa: E501

        :param events: The events of this Chapter.
        :type events: List[Event]
        """

        self._events = events
