# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntryList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, key: str=None, values: List[str]=None):  # noqa: E501
        """EntryList - a model defined in Swagger

        :param key: The key of this EntryList.  # noqa: E501
        :type key: str
        :param values: The values of this EntryList.  # noqa: E501
        :type values: List[str]
        """
        self.swagger_types = {
            'key': str,
            'values': List[str]
        }

        self.attribute_map = {
            'key': 'key',
            'values': 'values'
        }
        self._key = key
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'EntryList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EntryList of this EntryList.  # noqa: E501
        :rtype: EntryList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this EntryList.


        :return: The key of this EntryList.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this EntryList.


        :param key: The key of this EntryList.
        :type key: str
        """

        self._key = key

    @property
    def values(self) -> List[str]:
        """Gets the values of this EntryList.


        :return: The values of this EntryList.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values: List[str]):
        """Sets the values of this EntryList.


        :param values: The values of this EntryList.
        :type values: List[str]
        """

        self._values = values
