# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.entry import Entry  # noqa: F401,E501
from swagger_server import util


class Test(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, test_code: str=None, test_type: str=None, fields: List[Entry]=None):  # noqa: E501
        """Test - a model defined in Swagger

        :param test_code: The test_code of this Test.  # noqa: E501
        :type test_code: str
        :param test_type: The test_type of this Test.  # noqa: E501
        :type test_type: str
        :param fields: The fields of this Test.  # noqa: E501
        :type fields: List[Entry]
        """
        self.swagger_types = {
            'test_code': str,
            'test_type': str,
            'fields': List[Entry]
        }

        self.attribute_map = {
            'test_code': 'testCode',
            'test_type': 'testType',
            'fields': 'fields'
        }
        self._test_code = test_code
        self._test_type = test_type
        self._fields = fields

    @classmethod
    def from_dict(cls, dikt) -> 'Test':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Test of this Test.  # noqa: E501
        :rtype: Test
        """
        return util.deserialize_model(dikt, cls)

    @property
    def test_code(self) -> str:
        """Gets the test_code of this Test.

        unique id of an specific test done by a specific student.  # noqa: E501

        :return: The test_code of this Test.
        :rtype: str
        """
        return self._test_code

    @test_code.setter
    def test_code(self, test_code: str):
        """Sets the test_code of this Test.

        unique id of an specific test done by a specific student.  # noqa: E501

        :param test_code: The test_code of this Test.
        :type test_code: str
        """

        self._test_code = test_code

    @property
    def test_type(self) -> str:
        """Gets the test_type of this Test.

        identify the type of test  # noqa: E501

        :return: The test_type of this Test.
        :rtype: str
        """
        return self._test_type

    @test_type.setter
    def test_type(self, test_type: str):
        """Sets the test_type of this Test.

        identify the type of test  # noqa: E501

        :param test_type: The test_type of this Test.
        :type test_type: str
        """

        self._test_type = test_type

    @property
    def fields(self) -> List[Entry]:
        """Gets the fields of this Test.

        dictionary of strings where the key are questions of the test and the values the scores obtained for a question.  # noqa: E501

        :return: The fields of this Test.
        :rtype: List[Entry]
        """
        return self._fields

    @fields.setter
    def fields(self, fields: List[Entry]):
        """Sets the fields of this Test.

        dictionary of strings where the key are questions of the test and the values the scores obtained for a question.  # noqa: E501

        :param fields: The fields of this Test.
        :type fields: List[Entry]
        """

        self._fields = fields
